version: '3.7'

services:
    db:
        image: postgres:12.1-alpine
        restart: always
        environment:
            - TZ=Europe/Minsk
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - pgdata_12_1:/var/lib/postrgesql/data
        ports:
            - ${DB_PORT}:5432

    php:
        image: yiisoftware/yii2-php:7.2-apache
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        ports:
            - ${WEB_PORT}:80
        environment:
            PHP_ENABLE_XDEBUG: 1
            XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9000
            PHP_IDE_CONFIG: serverName=app

volumes:
    pgdata_12_1: